// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "cat-pool-20204124403336-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://cat-pool-20204124403336-hostingbucket-dev.s3-website.us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-2:158a1449-2829-4d2c-9257-d26cbc055d4e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_9It20Abjw",
    "aws_user_pools_web_client_id": "3mvp062oakc962uvp3t9t49kpp",
    "oauth": {}
};


export default awsmobile;
